In [1]:
#Import packages
import os
import pathlib

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import tensorflow as tf

from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras import layers
from tensorflow.keras import models
from IPython import display

In [2]:
#Download sample dataset
data_dir = pathlib.Path('data/mini_speech_commands')
if not data_dir.exists():
  tf.keras.utils.get_file(
      'mini_speech_commands.zip',
      origin="http://storage.googleapis.com/download.tensorflow.org/data/mini_speech_commands.zip",
      extract=True,
      cache_dir='.', cache_subdir='data')

In [3]:
#Get the target names (i.e. commands) from the data directory
commands = np.array(tf.io.gfile.listdir(str(data_dir)))
commands = commands[commands != 'README.md']
print('Commands:', commands)

Commands: ['right' 'go' '.DS_Store' 'no' 'left' 'stop' 'up' 'down' 'yes']


In [4]:
#Extract the names of the audio files in a list
filenames = tf.io.gfile.glob(str(data_dir) + '/*/*')

In [5]:
len(filenames)

8000

In [7]:
filenames[0]

'data/mini_speech_commands/right/988e2f9a_nohash_0.wav'

In [8]:
#Function to decode audio file
def decode_audio(audio_binary):
  audio, _ = tf.audio.decode_wav(audio_binary)
  return tf.squeeze(audio, axis=-1)

In [9]:
#Function to get the label of the audio file
def get_label(file_path):
  parts = tf.strings.split(file_path, os.path.sep)

  # Note: You'll use indexing here instead of tuple unpacking to enable this 
  # to work in a TensorFlow graph.
  return parts[-2] 

In [10]:
def get_waveform_and_label(file_path):
  label = get_label(file_path)
  audio_binary = tf.io.read_file(file_path)
  waveform = decode_audio(audio_binary)
  return waveform, label

In [11]:
test_wave, test_label = get_waveform_and_label(filenames[0])

In [12]:
test_wave

<tf.Tensor: shape=(16000,), dtype=float32, numpy=
array([-0.00064087, -0.00091553, -0.00088501, ..., -0.00048828,
       -0.00054932, -0.00085449], dtype=float32)>

In [13]:
test_label

<tf.Tensor: shape=(), dtype=string, numpy=b'right'>

In [15]:
!pip install tensorflow_io

     |████████████████████████████████| 22.8 MB 16.9 MB/s eta 0:00:01   |█████▋                          | 4.0 MB 4.7 MB/s eta 0:00:04
     |████████████████████████████████| 195.7 MB 17.6 MB/s eta 0:00:01     |████████████████▊               | 102.3 MB 27.4 MB/s eta 0:00:04     |█████████████████████████▊      | 157.2 MB 25.6 MB/s eta 0:00:02     |█████████████████████████████▌  | 180.3 MB 25.3 MB/s eta 0:00:01     |███████████████████████████████▉| 194.7 MB 17.6 MB/s eta 0:00:01
     |████████████████████████████████| 1.8 MB 14.4 MB/s eta 0:00:01     |███████▎                        | 419 kB 14.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 30.1 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB 15.0 MB/s eta 0:00:01
     |████████████████████████████████| 462 kB 32.1 MB/s eta 0:00:01
     |████████████████████████████████| 15.6 MB 10.2 MB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 11.4 MB/s eta 0:00:01
     |█████████████████████████

  Attempting uninstall: gast
    Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.31.0
    Uninstalling grpcio-1.31.0:
      Successfully uninstalled grpcio-1.31.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Attempting uninstall:

In [18]:
import tensorflow as tf
import tensorflow_io as tfio

AttributeError: module 'tensorflow._api.v2.experimental' has no attribute 'register_filesystem_plugin'

In [17]:
!pip install tensorflow